void showLego() {
// macro to visualize the lego plots generated by gAlive->RunLego
// M.S. 03 oct 07 - Many mods

// habso = 1/X   (inverse of absorbtion length)
// hradl = 1/Xo  (inverse of radiation length)

   gROOT->Reset();
   gStyle->SetOptStat("ne");

   TFile *file = new TFile("galice.root");

//   TFile *file = new TFile("geometry.root");

   file->ls();

   TH2F *hgcm2 = (TH2F*)file->Get("hgcm2");
   TH2F *habso = (TH2F*)file->Get("habso");   
   TH2F *hradl = (TH2F*)file->Get("hradl");

   if ((!hgcm2)||(!habso)||(!hradl)) return;

   printf("here\n");

   hradl->SetXTitle("X/X_{0}                #varphi");
   hradl->SetYTitle("#vartheta");
   hradl->GetZaxis()->SetLabelSize(0.03);

   Float_t theta = 10;
   Float_t phi   = 170;
   Int_t ncont   = 50;

//    TCanvas *cgcm2 = new TCanvas("cgcm2","gcm2",200,100,600,400);
//    hgcm2->Draw("colz");

//    TCanvas *cabso = new TCanvas("cabso","abso",100,50,600,400);
//    habso->Draw("colz");

   gStyle->SetPalette(1);

   TCanvas *cradl = new TCanvas("cradl","radl",10,10,1000,800);
   cradl->SetFillColor(10);
   cradl->GetFrame()->SetFillColor(10);

   hradl->Draw("colz");

   Int_t nBinX = hradl->GetNbinsX();
   Int_t nBinY = hradl->GetNbinsY();

   Int_t nBin = 0;
   Double_t radTot = 0;
   Double_t hgcm2Tot = 0;

   for (Int_t i=1; i<=nBinX; i++)
     for (Int_t j=1; j<=nBinY; j++) {
       nBin++;
       radTot += hradl->GetBinContent(i,j);
       hgcm2Tot += hgcm2->GetBinContent(i,j);
     };
   
   cout << "mean budget = " << (radTot/nBin) << endl;
   cout << "mean density = " << (hgcm2Tot/nBin) << endl;

   TLatex *text = new TLatex(150.0,140.0,"r_{min} = 35 ; r_{max} = 100 ; z_{max} = #pm 5 cm");
   text->SetTextAlign(33);
   text->SetTextSize(0.028);

   text->Draw();

}   
