name: Release

on:
  release:
  types: [published]
  
jobs:
  build_release:
    runs-on: ubuntu-18.04
    - run: |
       set -e
       echo ${{github.event.release.tag_name}} | grep -e "prod-20[0-9][0-9][0-1][0-9][0-3][0-9]"
       echo ${{secrets.PASS}} | kinit ${{secrets.PRINCIPAL}}
       curl -X POST -k --negotiate -u : ${{secrets.URL}} -H 'Content-Type: application/x-www-form-urlencoded' -d 'ALIDPG_TAG=${{github.event.release.tag_name}}'
       kdestroy
       
